name: Discord PR Notification

on:
  pull_request:
    types: [opened, reopened]

jobs:
  notify_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_PR_WEBHOOK }}
          DISCORD_USERNAME: GitHub
          DISCORD_AVATAR: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
        uses: Ilshidur/action-discord@master
        with:
          args: |
            새로운 PR이 열렸습니다! @lkhoony @baezzy1789 @이광훈 @배지훈
            PR: ${{ github.event.pull_request.html_url }}
            작성자: ${{ github.event.pull_request.user.login }}
            제목: ${{ github.event.pull_request.title }}
